### ISSUE TITLE
current netcdf4 (1.2.4) recipe broken?

### ISSUE THREAD

**Issue by jbusecke** [ContinuumIO/anaconda-recipes#101]
I am experiencing problems with the current version of netcdf4 in my environment.

I installed a fresh environment using this file

```
name: standard
dependencies:
  - python=2.7
  - xarray
  - basemap
  - netcdf4
  - jupyter
  - dask
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - scikit-image
  - pytest
  - future
  - flake8
  - pip:
    - codecov
    - pytest-cov
    - jupyter_contrib_nbextensions
    - jupyter_nbextensions_configurator
```
When I try to import netcdf4 I get the following error:

```python
import netCDF4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/juliusbusecke/anaconda2/envs/standard/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(/Users/juliusbusecke/anaconda2/envs/standard/lib/python2.7/site-packages/netCDF4/_netCDF4.so, 2): Library not loaded: @rpath/libmfhdf.0.dylib
  Referenced from: /Users/juliusbusecke/anaconda2/envs/standard/lib/libnetcdf.11.dylib
  Reason: image not found

```
Is this a know issue? 

The output of `conda list` is below for reference
```
backports                 1.0                      py27_0
backports_abc             0.5                      py27_0
basemap                   1.0.7               np111py27_0
bleach                    1.5.0                    py27_0
bokeh                     0.12.4                   py27_0
cairo                     1.14.8                        0
chest                     0.2.3                    py27_0
cloudpickle               0.2.2                    py27_0
codecov                   2.0.7                     <pip>
configparser              3.5.0                    py27_0
coverage                  4.3.4                     <pip>
curl                      7.49.0                        1
cycler                    0.10.0                   py27_0
dask                      0.14.1                   py27_0
dbus                      1.10.10                       0
decorator                 4.0.11                   py27_0
entrypoints               0.2.2                    py27_1
enum34                    1.1.6                    py27_0
expat                     2.1.0                         0
fontconfig                2.12.1                        3
freetype                  2.5.5                         2
functools32               3.2.3.2                  py27_0
future                    0.16.0                   py27_1
futures                   3.0.5                    py27_0
geos                      3.4.2                         0
get_terminal_size         1.0.0                    py27_0
glib                      2.50.2                        1
gst-plugins-base          1.8.0                         0
gstreamer                 1.8.0                         0
hdf4                      4.2.11                        0
hdf5                      1.8.17                        1
heapdict                  1.0.0                    py27_1
html5lib                  0.999                    py27_0
icu                       54.1                          0
ipykernel                 4.6.1                    py27_0
ipython                   5.3.0                    py27_0
ipython_genutils          0.2.0                    py27_0
ipywidgets                6.0.0                    py27_0
jbig                      2.1                           0
jinja2                    2.9.6                    py27_0
jpeg                      9b                            0
jsonschema                2.6.0                    py27_0
jupyter                   1.0.0                    py27_3
jupyter_client            5.0.1                    py27_0
jupyter_console           5.1.0                    py27_0
jupyter_core              4.3.0                    py27_0
libffi                    3.2.1                         1
libgcc                    5.2.0                         0
libgfortran               3.0.0                         1
libiconv                  1.14                          0
libnetcdf                 4.4.1                         0
libpng                    1.6.27                        0
libsodium                 1.0.10                        0
libtiff                   4.0.6                         3
libxcb                    1.12                          1
libxml2                   2.9.4                         0
locket                    0.2.0                    py27_1
markupsafe                0.23                     py27_2
matplotlib                2.0.0               np111py27_0
mistune                   0.7.4                    py27_0
mkl                       2017.0.1                      0
nbconvert                 5.1.1                    py27_0
nbformat                  4.3.0                    py27_0
netcdf4                   1.2.4               np111py27_0
networkx                  1.11                     py27_0
notebook                  5.0.0                    py27_0
numpy                     1.11.3                   py27_0
olefile                   0.44                     py27_0
openssl                   1.0.2k                        1
pandas                    0.19.2              np111py27_1
pandocfilters             1.4.1                    py27_0
partd                     0.3.7                    py27_0
path.py                   10.3.1                   py27_0
pathlib2                  2.2.1                    py27_0
pcre                      8.39                          1
pexpect                   4.2.1                    py27_0
pickleshare               0.7.4                    py27_0
pillow                    4.1.0                    py27_0
pip                       9.0.1                    py27_1
pixman                    0.34.0                        0
prompt_toolkit            1.0.14                   py27_0
ptyprocess                0.5.1                    py27_0
py                        1.4.33                   py27_0
pycairo                   1.10.0                   py27_0
pygments                  2.2.0                    py27_0
pyparsing                 2.1.4                    py27_0
pyqt                      5.6.0                    py27_2
pytest                    3.0.7                    py27_0
pytest-cov                2.4.0                     <pip>
python                    2.7.13                        0
python-dateutil           2.6.0                    py27_0
pytz                      2017.2                   py27_0
pywavelets                0.5.2               np111py27_0
pyyaml                    3.12                     py27_0
pyzmq                     16.0.2                   py27_0
qt                        5.6.2                         3
qtconsole                 4.3.0                    py27_0
readline                  6.2                           2
requests                  2.13.0                   py27_0
scandir                   1.5                      py27_0
scikit-image              0.13.0              np111py27_0
scipy                     0.19.0              np111py27_0
seaborn                   0.7.1                    py27_0
setuptools                27.2.0                   py27_0
simplegeneric             0.8.1                    py27_1
singledispatch            3.4.0.3                  py27_0
sip                       4.18                     py27_0
six                       1.10.0                   py27_0
sqlite                    3.13.0                        0
ssl_match_hostname        3.4.0.2                  py27_1
subprocess32              3.2.7                    py27_0
terminado                 0.6                      py27_0
testpath                  0.3                      py27_0
tk                        8.5.18                        0
toolz                     0.8.2                    py27_0
tornado                   4.5.1                    py27_0
traitlets                 4.3.2                    py27_0
wcwidth                   0.1.7                    py27_0
wheel                     0.29.0                   py27_0
widgetsnbextension        2.0.0                    py27_0
xarray                    0.9.3                    py27_0
xz                        5.2.2                         1
yaml                      0.1.6                         0
zeromq                    4.1.5                         0
zlib                      1.2.8                         3

```

**Comment by marbsrednas** [comment]
I am experiencing the same problem. 

The builds seem to be broken for netcdf>=1.2.4.

I am attaching the ImportErrors for version 1.2.4 (but I get different ImportErrors for 1.2.7):

dlopen(~/anaconda3/lib/python3.6/site-packages/netCDF4/_netCDF4.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libnetcdf.11.dylib
Referenced from: ~/anaconda3/lib/python3.6/site-packages/netCDF4/_netCDF4.cpython-36m-darwin.so
Reason: Incompatible library version: _netCDF4.cpython-36m-darwin.so requires version 12.0.0 or later, but libnetcdf.11.dylib provides version 11.0.0

Is this enough information?

Thanks very much for any help!

Bram

**Comment by wylecho** [comment]
@ghost I am experiencing exactly the same issue with you.

Python 3.6.5 |Anaconda custom (x86_64)| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4 as nc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File " ~/anaconda3/lib/python3.6/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen( ~/anaconda3/lib/python3.6/site-packages/netCDF4/_netCDF4.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libnetcdf.11.dylib
  Referenced from: ~/anaconda3/lib/python3.6/site-packages/netCDF4/_netCDF4.cpython-36m-darwin.so
  Reason: Incompatible library version: _netCDF4.cpython-36m-darwin.so requires version 12.0.0 or later, but libnetcdf.11.dylib provides version 11.0.0

Have you resolved this issue on Mac?

**Comment by jbusecke** [comment]
FYI, I have since then circumvented this problem by adding the [conda-forge](https://conda-forge.org) channel to my environment file. 
Perhaps this helps.

**Comment by wylecho** [comment]
@jbusecke  Thanks for your information.

I resolved this issue by following the [recommended installation](https://anaconda.org/anaconda/netcdf4) command:  `conda install -c anaconda netcdf4`. Actually this command installed a new version of netCDF4 package.

**Comment by mingwandroid** [comment]
No one should use `-c anaconda` ever. It's an internal-use only channel
that comes with some issues.

The correct invocation to install AD packages is always `-c defaults`.
