### ISSUE TITLE
qt 4.8.7_4 breaks pyqt 4.11.4 py34_4

### ISSUE THREAD

**Issue by davidh-ssec** [ContinuumIO/anaconda-recipes#40]
I have a package that depends on pyqt. After installing it in a fresh python 3.4 environment on my mac (and some coworkers) I get the following error when trying to run my application:

```
Traceback (most recent call last):
  File "/Users/davidh/anaconda/envs/sift_production/lib/python3.4/site-packages/cspov/__main__.py", line 26, in <module>
    app_object = app.use_app('pyqt4')
  File "/Users/davidh/anaconda/envs/sift_production/lib/python3.4/site-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/Users/davidh/anaconda/envs/sift_production/lib/python3.4/site-packages/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/Users/davidh/anaconda/envs/sift_production/lib/python3.4/site-packages/vispy/app/application.py", line 218, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "PyQt4":
dlopen(/Users/davidh/anaconda/envs/sift_production/lib/python3.4/site-packages/PyQt4/QtOpenGL.so, 2): Library not loaded: @rpath/libpng16.16.dylib
  Referenced from: /Users/davidh/anaconda/envs/sift_production/lib/libQtGui.4.8.7.dylib
  Reason: Incompatible library version: libQtGui.4.dylib requires version 39.0.0 or later, but libpng16.16.dylib provides version 34.0.0
```

After some googling I found that someone had success with downgrading qt to a earlier build, `qt=4.8.7=1`. After doing this everything runs fine.

Edit: Should issues like this go on `conda/conda` or here?

**Comment by ccordoba12** [comment]
What happens if you update libpng?

**Comment by davidh-ssec** [comment]
Just updated libpng from 1.6.17-0 to 1.6.22-0 and it seems to be working. I swear I tried that. Sorry and thanks.

**Comment by davidh-ssec** [comment]
Actually @ccordoba12 I still have at least a similar issue on Windows. See here:

```
(sift_dev) C:\Users\User>conda install pyqt
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Anaconda3\envs\sift_dev:

The following NEW packages will be INSTALLED:

    pyqt: 4.11.4-py34_7
    qt:   4.8.7-vc10_9  [vc10]

Proceed ([y]/n)?

Linking packages ...
        1 file(s) copied.                                                |   0%
[      COMPLETE      ]|##################################################| 100%

(sift_dev) C:\Users\User>python -c "from PyQt4 import QtCore"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemError: error return without exception set
```

**Comment by ccordoba12** [comment]
This was already reported in ContinuumIO/anaconda-issues#938. It only happens on Windows and with Python 3.4.

**Comment by davidh-ssec** [comment]
Thanks @ccordoba12. If I would have known that existed I wouldn't have mentioned it. It is pretty difficult to find issues dealing with anaconda since there are at least 3 repositories where users have been allowed to submit issues. Maybe I'll make an issue about that...

**Comment by ccordoba12** [comment]
@davidh-ssec, don't worry about it :-) I know it's hard to find issues, I'm just trying to consolidate the duplicate ones.
