### ISSUE TITLE
scipy test fails when mkl-rt is installed

### ISSUE THREAD

**Issue by davidslac** [ContinuumIO/anaconda-recipes#47]
If I build a conda environment with scipy and nose, and then do

```
python -c "import scipy; scipy.test('fast')"
```

it works. But if I add mkl-rt to the environment, then I get a failure, see below.

At some point I was running into isses with the new mkl numpy/scipy, and googling around led me to think that installing mkl-rt was a good idea, but I did get messages that implied it had some of the same files as the mkl package, which made me nervous. What is the difference? Why would someone want mkl-rt? It is hard to remove that package also, if you remove mkl-rt, then I think you remove some files that are also in mkl, as certain parts of scipy won't import anymore. I don't see a good way to 're-install' mkl to get it back. 

Anyways, maybe nobody is using mkl-rt, but thought I would share: here is the failure

```
======================================================================
FAIL: test_iterative.test_convergence(<function bicgstab at 0x7f0b8409a500>, <nonsymposdef>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/reg/neh/home/davidsch/.conda/envs/scipy/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/reg/neh/home/davidsch/.conda/envs/scipy/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/tests/test_iterative.py", line 196, in check_convergence
    assert_equal(info,0)
  File "/reg/neh/home/davidsch/.conda/envs/scipy/lib/python2.7/site-packages/numpy/testing/utils.py", line 379, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: -10
 DESIRED: 0
```

My conda environment is

```
(scipy) psanaphi103: ~ $ conda list
# packages in environment at /reg/neh/home/davidsch/.conda/envs/scipy:
#
libgfortran               3.0.0                         1    defaults
mkl                       11.3.3                        0    defaults
mkl-rt                    11.1                         p0    defaults
nose                      1.3.7                    py27_1    defaults
numpy                     1.11.1                   py27_0    defaults
openssl                   1.0.2h                        1    defaults
pip                       8.1.2                    py27_0    defaults
python                    2.7.12                        1    defaults
readline                  6.2                           2    defaults
scipy                     0.18.0              np111py27_0    defaults
setuptools                27.2.0                   py27_0    defaults
sqlite                    3.13.0                        0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py27_0    defaults
zlib                      1.2.8                         3    defaults
```

below is output from conda info.

```
(scipy) psanaphi103: ~ $ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : 2.0.1
         python version : 2.7.12.final.0
       requests version : 2.10.0
       root environment : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7  (read only)
    default environment : /reg/neh/home/davidsch/.conda/envs/scipy
       envs directories : /reg/neh/home/davidsch/.conda/envs
                          /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/envs
          package cache : /reg/neh/home/davidsch/.conda/envs/.pkgs
                          /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/pkgs
           channel URLs : file:///reg/g/psdm/sw/conda/channels/system-rhel7/linux-64/
                          file:///reg/g/psdm/sw/conda/channels/system-rhel7/noarch/
                          file:///reg/g/psdm/sw/conda/channels/psana-rhel7/linux-64/
                          file:///reg/g/psdm/sw/conda/channels/psana-rhel7/noarch/
                          file:///reg/g/psdm/sw/conda/channels/external-rhel7/linux-64/
                          file:///reg/g/psdm/sw/conda/channels/external-rhel7/noarch/
                          https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://conda.anaconda.org/conda-forge/linux-64/
                          https://conda.anaconda.org/conda-forge/noarch/
                          https://conda.anaconda.org/scikit-beam/linux-64/
                          https://conda.anaconda.org/scikit-beam/noarch/
                          file:///reg/g/psdm/sw/conda/channels/testing-rhel7/linux-64/
                          file:///reg/g/psdm/sw/conda/channels/testing-rhel7/noarch/
            config file : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/.condarc
           offline mode : False
```

if you google that error, you'll see references to issues with using optimization flags when building scipy: https://software.intel.com/en-us/forums/intel-math-kernel-library/topic/505993

**Comment by ilanschnell** [comment]
The `mkl-rt` (MKL-runtime) package is old, and conflicts with the newer `mkl` packages (which also install the MKL runtime.  Please don't install install them at the same time, as these packages will overwrite each others files.
