### ISSUE TITLE
Requests breaks ssl if crypto is not up-to-date

### ISSUE THREAD

**Issue by bkreider** [ContinuumIO/anaconda-recipes#69]
The latest requests can completely break conda!

The latest requests requires cryptography>1.3.4:  https://github.com/kennethreitz/requests/blob/master/setup.py#L97
```
'security': ['pyOpenSSL>=0.14', 'cryptography>=1.3.4', 'idna>=2.0.0'],
```

Issue upstream: https://github.com/kennethreitz/requests/issues/3710

I had this version of cryptography installed:
`cryptography              0.9.1   `

Stack trace:
```
 conda install conda
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.12
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /opt/anaconda  (writable)
    default environment : /opt/anaconda
       envs directories : /opt/anaconda/envs
          package cache : /opt/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
            config file : /opt/anaconda/.condarc
           offline mode : False



`$ /opt/anaconda/bin/conda install conda`




    Traceback (most recent call last):
      File "/opt/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/opt/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/opt/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/opt/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 403, in result
        return self.__get_result()
      File "/opt/anaconda/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/opt/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/opt/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/opt/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/opt/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/opt/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/opt/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/opt/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/opt/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/opt/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "/opt/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/opt/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'
```

My fix:  `conda install -f /opt/anaconda/pkgs/requests-2.10.0-py27_0.tar.bz2`

**Comment by bkreider** [comment]
Manually upgrading cryptography makes the latest requests (and conda) work as well:

```
conda install cryptography
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /opt/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cffi-1.9.1                 |           py27_0         193 KB  defaults
    cryptography-1.7.1         |           py27_0         468 KB  defaults
    ------------------------------------------------------------
                                           Total:         661 KB

The following packages will be UPDATED:

    cffi:         1.1.0-py27_0 None:///<unknown> --> 1.9.1-py27_0 defaults
    cryptography: 0.9.1-py27_0 None:///<unknown> --> 1.7.1-py27_0 defaults
    pyasn1:       0.1.7-py27_0 None:///<unknown> --> 0.1.9-py27_0 defaults

Proceed ([y]/n)? y

Fetching packages ...
cffi-1.9.1-py2 100% |###############################################################################################################################| Time: 0:00:00   1.73 MB/s
cryptography-1 100% |###############################################################################################################################| Time: 0:00:00   2.66 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################################################################################################################| 100%
0230-bkreider:mosh-1.2.6 bkreider$ conda install requests
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /opt/anaconda:

The following packages will be UPDATED:

    requests: 2.10.0-py27_0 defaults --> 2.12.4-py27_0 defaults

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|##################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################################################################################################################| 100%
```

**Comment by ilanschnell** [comment]
I wouldn't call this a bug, because `extra_requires` means optional dependencies.  We are going to fix this problem for `conda` by making `pyopenssl` a dependency of `conda`.

**Comment by bkreider** [comment]
It's not optional if you ever use SSL.  How does conda capture this dependency information?  Does ever conda package the depends on requests and also needs SSL need to manage the cryptography dependency in its metadata?  

It seems like a transitive dependency, that you have to know about because the requests conda package doesn't indicate the dependency.
