### ISSUE TITLE
PyQt 5 crashes on Linux

### ISSUE THREAD

**Issue by gqmelo** [ContinuumIO/anaconda-recipes#78]
When trying to use PyQt 5 on Linux in a stock miniconda installation it crashed with a seg fault. Isolating the problem, it happens when executing ```QGuiApplication::font``` method on Qt code.

# Steps to reproduce

```bash
~/miniconda2/bin/conda create -n test_qt python=3.5 qt=5 pyqt
source ~/miniconda2/bin/activate test_qt
python -c "from PyQt5.QtWidgets import QApplication; print(QApplication([])); from PyQt5.QtGui import QFont; print(QFont())"
```

This outputs:

```
<PyQt5.QtWidgets.QApplication object at 0x7f188c691808>
Segmentation fault (core dumped)
```

# gdb backtrace

```
#0  0x00007ffff4e0b5b9 in ?? () from /home/guilherme/miniconda2/envs/test_qt/lib/python3.5/site-packages/PyQt5/../../../libQt5Gui.so.5
#1  0x00007ffff4e0c56d in QGuiApplication::font() () from /home/guilherme/miniconda2/envs/test_qt/lib/python3.5/site-packages/PyQt5/../../../libQt5Gui.so.5
#2  0x00007ffff4eac5de in QFont::QFont() () from /home/guilherme/miniconda2/envs/test_qt/lib/python3.5/site-packages/PyQt5/../../../libQt5Gui.so.5
#3  0x00007fffedf7617d in init_type_QFont () from /home/guilherme/miniconda2/envs/test_qt/lib/python3.5/site-packages/PyQt5/QtGui.so
#4  0x00007fffee954e98 in ?? () from /home/guilherme/miniconda2/envs/test_qt/lib/python3.5/site-packages/sip.so
#5  0x00007ffff79b6daf in type_call (type=<optimized out>, args=0x7ffff7f81048, kwds=0x0) at Objects/typeobject.c:905
#6  0x00007ffff794f236 in PyObject_Call (func=0x7bddc8, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2165
#7  0x00007ffff7a29314 in do_call (nk=<optimized out>, na=0, pp_stack=0x7fffffffd448, func=0x7bddc8) at Python/ceval.c:4936
#8  call_function (oparg=<optimized out>, pp_stack=0x7fffffffd448) at Python/ceval.c:4732
#9  PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3236
#10 0x00007ffff7a2cb49 in _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0)
    at Python/ceval.c:4018
#11 0x00007ffff7a2ccd8 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=<optimized out>, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4039
#12 0x00007ffff7a2cd1b in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at Python/ceval.c:777
#13 0x00007ffff7a5487a in run_mod (arena=0x69bcc0, flags=0x7fffffffd710, locals=0x7ffff7f2f408, globals=0x7ffff7f2f408, filename=<optimized out>, mod=<optimized out>) at Python/pythonrun.c:976
#14 PyRun_StringFlags (str=0x7ffff7e62050 "from PyQt5.QtWidgets import QApplication; print(QApplication([])); from PyQt5.QtGui import QFont; print(QFont())\n", start=257, globals=0x7ffff7f2f408, locals=0x7ffff7f2f408, flags=0x7fffffffd710) at Python/pythonrun.c:900
#15 0x00007ffff7a54910 in PyRun_SimpleStringFlags (command=0x7ffff7e62050 "from PyQt5.QtWidgets import QApplication; print(QApplication([])); from PyQt5.QtGui import QFont; print(QFont())\n", flags=0x7fffffffd710) at Python/pythonrun.c:421
#16 0x00007ffff7a6e16e in run_command (cf=0x7fffffffd710, command=0x604460 L"from PyQt5.QtWidgets import QApplication; print(QApplication([])); from PyQt5.QtGui import QFont; print(QFont())\n") at Modules/main.c:279
#17 Py_Main (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:707
#18 0x0000000000400add in main (argc=3, argv=0x7fffffffd888) at ./Programs/python.c:65
```

# valgrind output

It shows a lot of things. This is what seems relevant:

```
==24070== Invalid read of size 8
==24070==    at 0x7BAF5B9: ??? (in /home/guilherme/miniconda2/envs/test_qt/lib/libQt5Gui.so.5.6.2)
==24070==    by 0x7BB056C: QGuiApplication::font() (in /home/guilherme/miniconda2/envs/test_qt/lib/libQt5Gui.so.5.6.2)
==24070==    by 0x7C505DD: QFont::QFont() (in /home/guilherme/miniconda2/envs/test_qt/lib/libQt5Gui.so.5.6.2)
==24070==    by 0xF09D17C: init_type_QFont (in /home/guilherme/miniconda2/envs/test_qt/lib/python3.5/site-packages/PyQt5/QtGui.so)
==24070==    by 0xE47DE97: ??? (in /home/guilherme/miniconda2/envs/test_qt/lib/python3.5/site-packages/sip.so)
==24070==    by 0x4F07DAE: type_call (typeobject.c:905)
==24070==    by 0x4EA0235: PyObject_Call (abstract.c:2165)
==24070==    by 0x4F7A313: do_call (ceval.c:4936)
==24070==    by 0x4F7A313: call_function (ceval.c:4732)
==24070==    by 0x4F7A313: PyEval_EvalFrameEx (ceval.c:3236)
==24070==    by 0x4F7DB48: _PyEval_EvalCodeWithName (ceval.c:4018)
==24070==    by 0x4F7DCD7: PyEval_EvalCodeEx (ceval.c:4039)
==24070==    by 0x4F7DD1A: PyEval_EvalCode (ceval.c:777)
==24070==    by 0x4FA5879: run_mod (pythonrun.c:976)
==24070==    by 0x4FA5879: PyRun_StringFlags (pythonrun.c:900)
==24070==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==24070== 
==24070== 
==24070== Process terminating with default action of signal 11 (SIGSEGV)
==24070==  Access not within mapped region at address 0x0
==24070==    at 0x7BAF5B9: ??? (in /home/guilherme/miniconda2/envs/test_qt/lib/libQt5Gui.so.5.6.2)
==24070==    by 0x7BB056C: QGuiApplication::font() (in /home/guilherme/miniconda2/envs/test_qt/lib/libQt5Gui.so.5.6.2)
==24070==    by 0x7C505DD: QFont::QFont() (in /home/guilherme/miniconda2/envs/test_qt/lib/libQt5Gui.so.5.6.2)
==24070==    by 0xF09D17C: init_type_QFont (in /home/guilherme/miniconda2/envs/test_qt/lib/python3.5/site-packages/PyQt5/QtGui.so)
==24070==    by 0xE47DE97: ??? (in /home/guilherme/miniconda2/envs/test_qt/lib/python3.5/site-packages/sip.so)
==24070==    by 0x4F07DAE: type_call (typeobject.c:905)
==24070==    by 0x4EA0235: PyObject_Call (abstract.c:2165)
==24070==    by 0x4F7A313: do_call (ceval.c:4936)
==24070==    by 0x4F7A313: call_function (ceval.c:4732)
==24070==    by 0x4F7A313: PyEval_EvalFrameEx (ceval.c:3236)
==24070==    by 0x4F7DB48: _PyEval_EvalCodeWithName (ceval.c:4018)
==24070==    by 0x4F7DCD7: PyEval_EvalCodeEx (ceval.c:4039)
==24070==    by 0x4F7DD1A: PyEval_EvalCode (ceval.c:777)
==24070==    by 0x4FA5879: run_mod (pythonrun.c:976)
==24070==    by 0x4FA5879: PyRun_StringFlags (pythonrun.c:900)
```

# Installed packages

```
$ conda list --show-channel-urls
# packages in environment at /home/guilherme/miniconda2/envs/test_qt:
#
dbus                      1.10.10                       0    defaults
expat                     2.1.0                         0    defaults
fontconfig                2.12.1                        2    defaults
freetype                  2.5.5                         2    defaults
glib                      2.50.2                        1    defaults
gst-plugins-base          1.8.0                         0    defaults
gstreamer                 1.8.0                         0    defaults
icu                       54.1                          0    defaults
jpeg                      9b                            0    defaults
libffi                    3.2.1                         1    defaults
libgcc                    5.2.0                         0    defaults
libiconv                  1.14                          0    defaults
libpng                    1.6.27                        0    defaults
libxcb                    1.12                          1    defaults
libxml2                   2.9.4                         0    defaults
openssl                   1.0.2k                        0    defaults
pcre                      8.39                          1    defaults
pip                       9.0.1                    py35_1    defaults
pyqt                      5.6.0                    py35_2    defaults
python                    3.5.2                         0    defaults
qt                        5.6.2                         3    defaults
readline                  6.2                           2    defaults
setuptools                27.2.0                   py35_0    defaults
sip                       4.18                     py35_0    defaults
sqlite                    3.13.0                        0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py35_0    defaults
xz                        5.2.2                         1    defaults
zlib                      1.2.8                         3    defaults
```

# conda info

```
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.12
         python version : 2.7.12.final.0
       requests version : 2.12.1
       root environment : /home/guilherme/miniconda2  (writable)
    default environment : /home/guilherme/miniconda2/envs/test_qt
       envs directories : /home/guilherme/miniconda2/envs
          package cache : /home/guilherme/miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /home/guilherme/miniconda2/.condarc
           offline mode : False
```

I tried to reproduce in C++:

```c++
#include <QtGui/QFont>
#include <QtWidgets/QApplication>

int main(int argc, char *argv[]) {
    QGuiApplication qapp(argc, argv);
    qapp.font();
    QFont font;
    printf("Successfully created\n");
}
```

and compile and run with:

```bash
g++ -o qt_example qt_example.cpp -I$CONDA_PREFIX/include -I$CONDA_PREFIX/include/qt -L $CONDA_PREFIX/lib -lQt5Widgets -lQt5Gui -lQt5Core -licui18n -licudata -licuuc
LD_LIBRARY_PATH=$CONDA_PREFIX/lib ./qt_example
```

but it works just fine.

All info above was obtained on an ```Ubuntu 16.10``` and conda packages ```Python 3.5```, ```Qt 5.6.2```, ```PyQt 5.6.0``` but I've also tried some other configuration:
- python 2.7, 3.5 and 3.6
- qt 5.6.0 and 5.6.2 (all builds)
- pyqt 5.6.0 (all builds)
- Ubuntu 16.04 VM, CentOS 6 chroot

**Comment by gqmelo** [comment]
Sorry, my bad. I was investigating another crash and did not notice my minimal example had a bug. Assigning QApplication to a variable does not crash anymore: ```python -c "from PyQt5.QtWidgets import QApplication; app = QApplication([]); from PyQt5.QtGui import QFont; print(QFont())"```
